### ISSUE TITLE
baxter_bridge build fails

### ISSUE THREAD

**Issue by sahilgaurkar** [CentraleNantesRobotics/baxter_common_ros2#5]
**Issue:**
Baxter_bridge build fails

**Output:**

Starting >>> baxter_bridge
--- stderr: baxter_bridge                               
In file included from /home/sahil/TEmp/ros2_baxter/src/baxter_common_ros2/baxter_bridge/src/baxter_bridge.cpp:1:
/home/sahil/TEmp/ros2_baxter/src/baxter_common_ros2/baxter_bridge/include/baxter_bridge/solve_ik.h:7:10: fatal error: baxter_core_msgs/SolvePositionIK.h: No such file or directory
    7 | #include <baxter_core_msgs/SolvePositionIK.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/bridge.dir/build.make:76: CMakeFiles/bridge.dir/src/baxter_bridge.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:593: CMakeFiles/bridge.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< baxter_bridge [11.3s, exited with code 2]

**Environment:**
Ubuntu: 22.04.2 LTS
ROS: humble

**Steps to Reproduce:**
1. clone repo
2. build: colcon build

It would be very helpful if you could point me in the right direction to resolve this issue.
Thank you

**Comment by oKermorgant** [comment]
Hi,
Indeed, the ROS 1 messages were not shipped with the bridge.
It should now be fine.
Note that you will need a few ROS 1 packages to have the bridge compile.

**Comment by lbartenstein** [comment]
Hello @oKermorgant :) 

I have an almost similiar issue. 

System:
Ubuntu 20.04 on VM
ROS1 Noetic installed as binary
ROS2 Foxy installed as source

Steps to reproduce: 

1. clone repo 
2. source ~/ros2_foxy/install/setup.bash
3. colcon build 
4. the following error occurs:


--- stderr: baxter_bridge                                          
/usr/bin/ld: /opt/ros/noetic/lib/libkdl_parser.so: undefined reference to `urdf::Model::initParam(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bridge.dir/build.make:390: bridge] Error 1
make[1]: *** [CMakeFiles/Makefile2:391: CMakeFiles/bridge.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< baxter_bridge [1min 28s, exited with code 2]



It also happens when I source both ROS1 with /opt/ros/noetic/setup.bash and ROS2 in any order. 

Before, I installed the baxter_legacy repo from you on the same VM which was working fine. 

Any help would be appreciated. 
Thanks in advance!

**Comment by oKermorgant** [comment]
Hi,

It is strange that CMake tries to link with the ROS 1 urdf library, that should not appear anywhere.
This is a ROS 2 package and ROS 1 should not be sourced at all.

**Comment by lbartenstein** [comment]
Hello, 

thanks for the answer. 

I tried again on a freshly started VM, only sourcing ROS2. 

Here is the output from printenv | grep ROS:
ROS_VERSION=2
ROS_PYTHON_VERSION=3
ROS_LOCALHOST_ONLY=0
ROS_DISTRO=foxy

Then I cloned the repo again and, after renaming baxter_common_ros2 to src, I directly try colcon build. 
The error is still the same. 
baxter_bridge takes over 1 minute to build, mostly standing at 97%, then failing. 

The VM has 13184 MB of RAM and can use 8 Cores.

**Comment by oKermorgant** [comment]
I found a slight bug in the deb files generation, keep in touch.

**Comment by oKermorgant** [comment]
Maybe try with the updated Debian files (`ros-baxter[noetic]_1.3.1.deb` for your version I guess)

**Comment by lbartenstein** [comment]
Hello again, 

today I tried with a freshly installed VM and the error still occurs. 

Steps to reproduce:

1. Setup new virtual machine on VMWare Workstation 16 Player with identical stats, OS is Ubuntu 20.04. 
2. Install Updates Ubuntu offers me, as well as Terminator.
3. Install ROS1 Noetic from binary
4. Install ROS2 Foxy from source 
5. git clone your baxter_legacy repo and install the ros-baxter[noetic]_1.3.1.deb
6. git clone this repo
7. source ~/ros2_foxy/install/setup.bash 
8. colcon build 

Error is the same. 

How is your Setup with the Baxter, are you using Noetic + Foxy on 20.04 as well? 

Thanks in advance! 

Best regards, 
Lukas

**Comment by oKermorgant** [comment]
I have just reinstalled it from scratch, but using binaries for Foxy.
Maybe something strange happens when Foxy is installed from source but I'll let you find it, as it seems simpler to get the binaries.

**Comment by lbartenstein** [comment]
Hello again and happy new year, 

using the binaries for foxy worked for me as well, thanks!

**Comment by oKermorgant** [comment]
Perfect, closing the issue with a happy new year indeed!
